name: Rebuild website

on:
  # Allows external webhook trigger
  workflow_dispatch:
    types:
      - webhook
jobs:
  frontEndBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: custom_webhook
        run: echo "Hello custom webhook"
